# Modules

**Learning objectives:**

- Introduce *modules*
- 

## Modules defined

modules:

* an object that encapsulates state
* can be of any complexity (e.g. layer, or models consisting of layers)


## Built-in `nn_module()s` {-}


```{r}
library(torch)

l <- nn_linear(in_features = 5, out_features = 16)
l
```


## Building up a Model {-}

### Sequential Models

multi-layer perceptron (MLP)

```{r}
mlp <- nn_sequential(
  nn_linear(10, 32),
  nn_relu(),
  nn_linear(32,64),
  nn_relu(),
  nn_linear(64,1)
)
```


### 7.2.2

```{r}
my_linear <- nn_module(
  initialize = function(in_features, out_features){
    self$w <- nn_parameter(torch_randn(in_features, out_features))
    self$b <- nn_parameter(torch_zeros(out_features))
  },
  forward = function(input){
    input$mm(self$w) + self$b
  }
)
```

```{r}
l <- my_linear(7, 1)
l
```


##  {-}

## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
